# Generated by Django 4.2.19 on 2025-02-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('linked_in', models.URLField(blank=True, max_length=255)),
                ('contact_info', models.EmailField(blank=True, max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('office_hours', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['full_name', 'course'], name='Professors__full_na_3e6c16_idx')],
            },
        ),
    ]
