# Generated by Django 4.2.19 on 2025-02-19 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_alter_course_course_type_delete_coursetype'),
        ('Professors', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='professor',
            new_name='Professors__full_na_20866d_idx',
            old_name='Professors__full_na_3e6c16_idx',
        ),
        migrations.AlterField(
            model_name='professor',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='Courses.course'),
        ),
    ]
