# Generated by Django 4.2.19 on 2025-03-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='contact_info',
            field=models.EmailField(max_length=255),
        ),
    ]
