# Generated by Django 4.2.19 on 2025-02-19 04:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampusService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('contact', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$', message='Enter a valid phone number')])),
                ('service_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='campus_services', to='CampusServices.service')),
            ],
        ),
    ]
