# Generated by Django 4.2.19 on 2025-03-03 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CampusServices', '0002_remove_campusservice_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusservice',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_services', to='CampusServices.service'),
        ),
    ]
