# Generated by Django 4.2.19 on 2025-03-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusServices', '0003_alter_campusservice_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusservice',
            name='service',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
