# Generated by Django 4.2.19 on 2025-03-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CampusServices', '0004_alter_campusservice_service_delete_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campusservice',
            name='service',
        ),
    ]
