# Generated by Django 4.2.19 on 2025-02-19 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Professors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[('LECT', 'Lecture'), ('LAB', 'Laboratory'), ('TUTOR', 'Tutorial')], default='LECT', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('course_name', models.CharField(max_length=255)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Professors.professor')),
            ],
        ),
    ]
