# Generated by Django 4.2.19 on 2025-02-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_coursetype_alter_course_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='CourseType',
        ),
    ]
