# Generated by Django 4.2.19 on 2025-02-19 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_alter_course_course_type_delete_coursetype'),
    ]

    operations = [
    ]
