# Generated by Django 4.2.19 on 2025-03-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='club',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
