# Generated by Django 4.2.19 on 2025-02-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, unique=True)),
                ('answer', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['question'],
                'indexes': [models.Index(fields=['question'], name='FAQs_questi_questio_8d1427_idx')],
            },
        ),
    ]
