# Generated by Django 4.2.19 on 2025-02-19 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportantRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('responsibility', models.TextField(blank=True)),
                ('room_type', models.CharField(choices=[('CLASSROOM', 'Classroom'), ('LAB', 'Laboratory'), ('OFFICE', 'Office')], default='CLASSROOM', max_length=10)),
                ('floor_number', models.PositiveIntegerField()),
                ('building_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='important_rooms', to='ImportantRooms.buildingname')),
            ],
            options={
                'ordering': ['building_name', 'floor_number', 'room_number'],
                'indexes': [models.Index(fields=['room_number', 'floor_number'], name='ImportantRo_room_nu_560dec_idx')],
            },
        ),
    ]
