# Generated by Django 4.2.19 on 2025-03-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImportantRooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantroom',
            name='room_type',
            field=models.CharField(max_length=100),
        ),
    ]
