# Generated by Django 4.2.19 on 2025-03-04 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ImportantRooms', '0002_alter_importantroom_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='importantroom',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='important_rooms', to='ImportantRooms.roomtype'),
        ),
    ]
