# Generated by Django 4.2.19 on 2025-03-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImportantRooms', '0003_roomtype_alter_importantroom_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantroom',
            name='floor_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='importantroom',
            name='responsibility',
            field=models.TextField(),
        ),
    ]
