# Generated by Django 4.2.19 on 2025-02-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
