# Generated by Django 4.2.19 on 2025-03-04 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_alter_event_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
    ]
