# Generated by Django 4.2.19 on 2025-03-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_remove_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('date', 'venue'), name='unique_event_per_venue'),
        ),
    ]
